###
http://localhost:1337/api/evaluacion-usuarios?filters[TipoFormulario][$eq]=ISO27001&populate=*

###
http://localhost:1337/api/evaluacion-usuarios

###

http://localhost:1337/api/preguntas?filters[marco_normativo][$eq]=ISO27001${marco}&sort=orden:asc


###
http://localhost:1337/api/preguntas?filters[marco_normativo][$eq]=ISO27001&sort=orden:asc

###
http://localhost:1337/api/capacitacions